### ISSUE TITLE
Robocop fails when you execute it in a different path

### ISSUE THREAD

**Issue by szabolcstoth** [MarketSquare/robotframework-robocop#244]
**Describe the bug**
Scenario: I would like to execute Robocop to check a folder in a different path, it fails due `relative_to` throws a `ValueError`.

**To Reproduce**
```bash
$ pwd
/home/szabolcs/repositories
$ robocop ~/playground/test_data.robot
```
This will throw the following error:
```
Traceback (most recent call last):
  File "/home/szabolcs/virtualenvs/default/bin/robocop", line 8, in <module>
    sys.exit(run_robocop())
  File "/home/szabolcs/virtualenvs/default/lib/python3.8/site-packages/robocop/run.py", line 226, in run_robocop
    linter.run()
  File "/home/szabolcs/virtualenvs/default/lib/python3.8/site-packages/robocop/run.py", line 46, in run
    self.run_checks()
  File "/home/szabolcs/virtualenvs/default/lib/python3.8/site-packages/robocop/run.py", line 94, in run_checks
    self.report(issue)
  File "/home/szabolcs/virtualenvs/default/lib/python3.8/site-packages/robocop/run.py", line 107, in report
    source_rel = Path(rule_msg.source).relative_to(self.root)
  File "/usr/lib/python3.8/pathlib.py", line 904, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/home/szabolcs/playground/test_data5.robot' does not start with '/home/szabolcs/repositories'
```

**Expected behavior**
The previously mentioned example worked with 1.1.0.
Is this an expected behavior?

**Comment by bhirsz** [comment]
No, it's regression (and severe one!) caused by this #222

**Comment by bhirsz** [comment]
On quick glance we should resolve self.root to be absolute path first -> I could take a look into it later

**Comment by bhirsz** [comment]
It should work with replacing this line in run.py:
```
source_rel = Path(rule_msg.source).relative_to(self.root)
```

with

```
source_rel = os.path.relpath(Path(rule_msg.source).expanduser(), self.root)
```

When I will be near PC I can test it - or you can do it.

**Comment by bhirsz** [comment]
@szabolcstoth could you checkout to this branch  fix/relative_paths , install from source code (pip install -e . when in robotframework-robocop directory) and test if it's fixed? I might to add extra precautions later for relative_to command, but for now just want to fix existing issue.

**Comment by szabolcstoth** [comment]
@bhirsz it seems that after the fix it still not works.

With the working version:
```bash
$ robocop --version
1.1.0
$ robocop ~/playground/test_data.robot
/home/szabolcs/playground/test_data.robot:1:0 [W] 0509 Section is empty
```

After I updated it:
```bash
$ git status
On branch fix/relative_paths
Your branch is up to date with 'origin/fix/relative_paths'.

nothing to commit, working tree clean
```
```bash
$ pip install -e .
Obtaining file:///home/szabolcs/repositories/marketsquare/robotframework-robocop
Requirement already satisfied: robotframework>=3.2.1 in /home/szabolcs/virtualenvs/default/lib/python3.8/site-packages (from robotframework-robocop==1.2.1) (3.2.2)
Installing collected packages: robotframework-robocop
  Attempting uninstall: robotframework-robocop
    Found existing installation: robotframework-robocop 1.1.0
    Uninstalling robotframework-robocop-1.1.0:
      Successfully uninstalled robotframework-robocop-1.1.0
  Running setup.py develop for robotframework-robocop
Successfully installed robotframework-robocop
```

I tried it:
```bash
$ robocop --version
1.2.1
(default) szabolcs@tanith-pc:~/repositories$ robocop ~/playground/test_data.robot
Traceback (most recent call last):
  File "/home/szabolcs/virtualenvs/default/bin/robocop", line 11, in <module>
    load_entry_point('robotframework-robocop', 'console_scripts', 'robocop')()
  File "/home/szabolcs/repositories/marketsquare/robotframework-robocop/robocop/run.py", line 226, in run_robocop
    linter.run()
  File "/home/szabolcs/repositories/marketsquare/robotframework-robocop/robocop/run.py", line 46, in run
    self.run_checks()
  File "/home/szabolcs/repositories/marketsquare/robotframework-robocop/robocop/run.py", line 94, in run_checks
    self.report(issue)
  File "/home/szabolcs/repositories/marketsquare/robotframework-robocop/robocop/run.py", line 107, in report
    source_rel = Path(rule_msg.source).relative_to(self.root)
  File "/usr/lib/python3.8/pathlib.py", line 904, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/home/szabolcs/playground/test_data.robot' does not start with '/home/szabolcs/repositories'
```
