### ISSUE TITLE
Error when using {rule_name} in a --format output

### ISSUE THREAD

**Issue by rdagum** [MarketSquare/robotframework-robocop#368]
**Describe the bug**
When passing this parameter to robocop `-f "{source_rel}:robocop:{line}: [{rule_id}({rule_name}), {severity}] {desc}"` it errors out with:

```
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "X:\Projects\mobile_automation\.temp\pvenv\lib\site-packages\robocop\__main__.py", line 4, in <module>
    robocop.run_robocop()
  File "X:\Projects\mobile_automation\.temp\pvenv\lib\site-packages\robocop\run.py", line 288, in run_robocop
    linter.run()
  File "X:\Projects\mobile_automation\.temp\pvenv\lib\site-packages\robocop\run.py", line 79, in run
    self.run_checks()
  File "X:\Projects\mobile_automation\.temp\pvenv\lib\site-packages\robocop\run.py", line 125, in run_checks
    self.report(issue)
  File "X:\Projects\mobile_automation\.temp\pvenv\lib\site-packages\robocop\run.py", line 152, in report
    self.log_message(source=rule_msg.source,
  File "X:\Projects\mobile_automation\.temp\pvenv\lib\site-packages\robocop\run.py", line 164, in log_message
    self.write_line(self.config.format.format(**kwargs))
KeyError: 'rule_name'
```

**Comment by bhirsz** [comment]
It should be "name" instead of "rule_name". It looks like some of our docs use "rule_name" - I consider this as a bug and I will fix it.
