### ISSUE TITLE
Parsing of config file fails if lines are swapped

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-robocop#402]
**Describe the bug**
If my config file looks exactly like this:
```
-c wrong-case-in-keyword-name:convention:first_word_capitalized
-c wrong-case-in-keyword-name:severity:E
```
everything is OK. However, when those lines are swapped:
```
-c wrong-case-in-keyword-name:severity:E
-c wrong-case-in-keyword-name:convention:first_word_capitalized
```
I am getting the following error running `robocop`:
```
Traceback (most recent call last):
File "c:\users\cen89549\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main                                                                                                                                  "__main__", mod_spec)
File "c:\users\cen89549\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code                                                                                                                                             exec(code, run_globals)
File "C:\Users\cen89549\AppData\Local\Programs\Python\Python37\Scripts\robocop.exe\__main__.py", line 7, in
File "c:\users\cen89549\appdata\local\programs\python\python37\lib\site-packages\robocop\run.py", line 293, in run_robocop                                                                                                                      linter.run()
File "c:\users\cen89549\appdata\local\programs\python\python37\lib\site-packages\robocop\run.py", line 79, in run                                                                                                                               self.reload_config()
File "c:\users\cen89549\appdata\local\programs\python\python37\lib\site-packages\robocop\run.py", line 75, in reload_config                                                                                                                     self.configure_checkers_or_reports()
File "c:\users\cen89549\appdata\local\programs\python\python37\lib\site-packages\robocop\run.py", line 274, in configure_checkers_or_reports                                                                                  configurable = msg.get_configurable(param)
AttributeError: 'NoneType' object has no attribute 'get_configurable'
```

I guess this should work, so the described behaviour is a bug.

Robocop 1.8.1

**Comment by bhirsz** [comment]
Will this be enough::
```
robocop --ext-rules RobocopRules .
```
where RobocopRules are for example:
```
RobocopRules/
RobocopRules/__init__.py
RobocopRules/some_rules.py
setup.py
```
inside __init__.py:
```
from .some_rules import MissingKeywordName

all = ['MissingKeywordName']
```
inside some_rules.py:
```
from robocop.checkers import VisitorChecker
from robocop.rules import RuleSeverity


class MissingKeywordName(VisitorChecker):
    """ Checker for missing keyword name. """
    rules = {
        "9903": (
            "external-rule",
            "This is external rule",
            RuleSeverity.INFO
        )
    }

    def visit_KeywordCall(self, node):  # noqa
        if node.keyword and 'Dummy' not in node.keyword:
            self.report("external-rule", node=node)

```

Or you need more sofisticated methods of importing, ie dotted import?:
```
robocop --ext-rules mymodule.nested
```

I've implemented first example and it should be part of next release. I could improve it by adding other methods of importing (such as mentioned dotted import) but I'm not sure if it would be ready for next release.
