### ISSUE TITLE
[Bug] Defining a keyword named "GIVEN", "WHEN", "THEN", "AND" throws an exception

### ISSUE THREAD

**Issue by d-biehl** [MarketSquare/robotframework-robocop#549]
### What happened?

given this piece of code:

```robotframework
*** Test Cases ***
First
    GIVEN

*** Keywords ***
GIVEN
    Log To Console    hi
```
when the code is analysed by robocop
then robocop throws the following exception:

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\Scripts\robocop.exe\__main__.py", line 7, in <module>
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\run.py", line 317, in run_robocop
    linter.run()
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\run.py", line 84, in run
    self.run_checks()
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\run.py", line 129, in run_checks
    found_issues = self.run_check(model, str(file))
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\run.py", line 148, in run_check
    for issue in checker.scan_file(ast_model, filename, source, templated)
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\checkers\__init__.py", line 103, in scan_file
    self.visit_File(ast_model)
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\checkers\__init__.py", line 108, in visit_File
    self.generic_visit(node)
  File "C:\Program Files\Python310\lib\ast.py", line 418, in generic_visit
    self.visit(item)
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robot\parsing\model\visitor.py", line 49, in visit
    visitor(node)
  File "C:\Program Files\Python310\lib\ast.py", line 418, in generic_visit
    self.visit(item)
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robot\parsing\model\visitor.py", line 49, in visit
    visitor(node)
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\checkers\naming.py", line 165, in visit_Keyword
    self.check_keyword_naming(node.name, node)
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\checkers\naming.py", line 194, in check_keyword_naming
    self.check_bdd_keywords(keyword_name, node)
  File "C:\Users\daniel\.virtualenvs\project2-ZE2vXZAG\lib\site-packages\robocop\checkers\naming.py", line 209, in check_bdd_keywords
    arg = node.get_token(Token.ARGUMENT)
AttributeError: 'Keyword' object has no attribute 'get_token'
```

---
Writing bugs in BDD style is also possible ;-)

### Operating System

Windows

### Robocop version

1.12.0

**Comment by bhirsz** [comment]
Thanks for the report - it looks similar to issue with Run Keyword If (checker for keyword naming assumed that anything matching Run Keyword If name is keyword call even if it was keyword definition). I will look into it
