### ISSUE TITLE
[Bug] Robocop fails since 23rd of march (robotframework 5.0 ?)

### ISSUE THREAD

**Issue by Rowix** [MarketSquare/robotframework-robocop#579]
### What happened?

Yesterday [robotframework 5.0](https://pypi.org/project/robotframework/) was released and since today a simple docker like:
```
FROM python:3.9-alpine

RUN apk add --update \
    bash \
    make \
    jq \
    gcc \
    musl-dev && \
  pip install --upgrade \
    yamllint \
    j2cli \
    openapi-spec-validator \
    yq \
    cfn-lint \
    robotframework-robocop
```
fails with messages like:
```
documentation can be found here https://robocop.readthedocs.io/en/stable/rules.html
$ robocop --report rules_by_error_type --threshold E -g Dev_argumentfile.robot -g Staging_argumentfile.robot
Traceback (most recent call last):
  File "/usr/local/bin/robocop", line 8, in <module>
    sys.exit(run_robocop())
  File "/usr/local/lib/python3.9/site-packages/robocop/run.py", line 317, in run_robocop
    linter.run()
  File "/usr/local/lib/python3.9/site-packages/robocop/run.py", line 84, in run
    self.run_checks()
  File "/usr/local/lib/python3.9/site-packages/robocop/run.py", line 1[29](https://gitlab.enoro.com/Utilytics/svc-grid-exchange-point/-/jobs/212880#L29), in run_checks
    found_issues = self.run_check(model, str(file))
  File "/usr/local/lib/python3.9/site-packages/robocop/run.py", line 148, in run_check
    for issue in checker.scan_file(ast_model, filename, source, templated)
  File "/usr/local/lib/python3.9/site-packages/robocop/checkers/__init__.py", line 103, in scan_file
    self.visit_File(ast_model)
  File "/usr/local/lib/python3.9/site-packages/robocop/checkers/__init__.py", line 108, in visit_File
    self.generic_visit(node)
  File "/usr/local/lib/python3.9/ast.py", line [41](https://gitlab.enoro.com/Utilytics/svc-grid-exchange-point/-/jobs/212880#L41)5, in generic_visit
    self.visit(item)
  File "/usr/local/lib/python3.9/site-packages/robot/parsing/model/visitor.py", line [49](https://gitlab.enoro.com/Utilytics/svc-grid-exchange-point/-/jobs/212880#L49), in visit
    visitor(node)
  File "/usr/local/lib/python3.9/ast.py", line 417, in generic_visit
    self.visit(value)
  File "/usr/local/lib/python3.9/site-packages/robot/parsing/model/visitor.py", line 49, in visit
    visitor(node)
  File "/usr/local/lib/python3.9/site-packages/robocop/checkers/errors.py", line 101, in visit_Statement
    self.parse_errors(node)
  File "/usr/local/lib/python3.9/site-packages/robocop/checkers/errors.py", line 110, in parse_errors
    self.handle_error(node, node.error)
AttributeError: 'SectionHeader' object has no attribute 'error'
Cleaning up project directory and file based variables
```

It seems that robotframework-robocop also installs robotframework, so for now the workarround has been:
```
FROM python:3.9-alpine

RUN apk add --update \
    bash \
    make \
    jq \
    gcc \
    musl-dev && \
  pip install --upgrade \
    yamllint \
    j2cli \
    openapi-spec-validator \
    yq \
    cfn-lint \
    pip install robotframework==4.1.3 \
    robotframework-robocop
```

### Operating System

Docker python:3.9-alpine

### Robocop version

1.12.0

**Comment by bhirsz** [comment]
Hi, thank you for reporting this issue - it's most likely related to the fact that we didn't release Robocop yet. We shall do it today and it should resolve any problems. I will let you know when it happens so you can confirm/deny if the issue is fixed.

**Comment by Rowix** [comment]
@bhirsz  it starts looking better.

using:
```
$ robocop -v
2.0.0
$ robot --version || true
Robot Framework 5.0 (Python 3.9.11 on linux)
```
(apparently "robot --version" results in an wrong exit status)

Gave the expected results for:
```
robocop --report rules_by_error_type --threshold E -g Dev_argumentfile.robot -g Staging_argumentfile.robot
```
but not for:
```
robocop --threshold W -g Dev_argumentfile.robot -g Staging_argumentfile.robot --exclude 0305 --exclude 0504 --exclude 0505 --exclude 0506 --exclude 0507 --exclude 0508 --exclude 0201
```

It now doesn't output some 0202, 0302, 0702 warnings but i didn't investigate if this was a bug or a fix ;)

**Comment by bhirsz** [comment]
0202 ("missing-doc-test-case") wasn't updated - do you have any example on hand what is not catched but should?

0302 - "wrong-case-in-keyword-name" was reworked and it will be also updated (it's quite problematic rule with many edge cases, symbols that should be ignored..)

0702 - "missing-space-after-comment" - do you have  example? It actually should output more warnings now because we didn't enter some specific data models

**Comment by Rowix** [comment]
Sorry didn't have time earlier to react earlier, But what would be the need, an actual test case or an example?
at least regarding the 0702 i saw that comments which were in the middle of test case weren't seen by the new version.

The only thing i saw was two different pipeline results and with robocop 2.0 it was just more forgiving compare to the previous version.

**Comment by bhirsz** [comment]
An example is enough - anything that I can use to narrow down any possible bug. I will add more test data to 0702 and see if there is problem - Robocop in 2.0 should catch the same or more issues.

**Comment by bhirsz** [comment]
Closing as stale issue - if the issue is still happening please re-open this issue or open new issue with new details.
