### ISSUE TITLE
[Bug] robocop fails with `AttributeError: 'NoneType' object has no attribute 'data_tokens'`

### ISSUE THREAD

**Issue by oboehmer** [MarketSquare/robotframework-robocop#582]
### What happened?

Tried out robocop on some of our test suites, and I see a crash examining our test suites

```
root@7f1836e96e29:/home/cisco/cxta# robocop --exclude wrong-case-in-keyword-name tests/integration/robot_files/
[..many warnings removed..]

Traceback (most recent call last):
  File "/venv/bin/robocop", line 8, in <module>
    sys.exit(run_robocop())
  File "/venv/lib/python3.8/site-packages/robocop/run.py", line 280, in run_robocop
    raise err
  File "/venv/lib/python3.8/site-packages/robocop/run.py", line 270, in run_robocop
    linter.run()
  File "/venv/lib/python3.8/site-packages/robocop/run.py", line 81, in run
    self.run_checks()
  File "/venv/lib/python3.8/site-packages/robocop/run.py", line 125, in run_checks
    found_issues = self.run_check(model, str(file))
  File "/venv/lib/python3.8/site-packages/robocop/run.py", line 143, in run_check
    for issue in checker.scan_file(ast_model, filename, source, templated)
  File "/venv/lib/python3.8/site-packages/robocop/checkers/__init__.py", line 103, in scan_file
    self.visit_File(ast_model)
  File "/venv/lib/python3.8/site-packages/robocop/checkers/spacing.py", line 367, in visit_File
    self.check_empty_lines_after_section(section)
  File "/venv/lib/python3.8/site-packages/robocop/checkers/spacing.py", line 405, in check_empty_lines_after_section
    section_name=get_section_name(section),
  File "/venv/lib/python3.8/site-packages/robocop/utils/misc.py", line 320, in get_section_name
    for token in node.header.data_tokens:
AttributeError: 'NoneType' object has no attribute 'data_tokens'
Fatal exception occurred. You can create an issue at https://github.com/MarketSquare/robotframework-robocop/issues/new/choose . Thanks!
```

I am able to isolate the issue to a specific test suite:

```
## Unit test file for cxta_ccdiff.py keywords
#
*** Settings ***

Library    BuiltIn
Library    OperatingSystem
Library    CXTA
Resource   cxta.robot
Force Tags  diff

*** Variables ***

# Directory where configs are stored
${dir}      tests/datafiles/cxta_ccdiff-configs

*** Test Cases ***

ios-diff
    @{result}=   use ciscoconfdiff to compare ios configs "${dir}/ios-1.txt" and "${dir}/ios-2.txt"
    verify result   ${result}[0]   ${dir}/ios-expected-diff1.txt
    verify result   ${result}[1]   ${dir}/ios-expected-diff2.txt
```

but when I take the file and put it elsewhere, robocop processes it just fine.. so you might actually have challenges reproducing this in your environment..

When I add a breakpoint before the failure, I see

```
319  	def get_section_name(node):
320  	    if node.header is None:
321  	        breakpoint()
(Pdb) p node
<robot.parsing.model.blocks.CommentSection object at 0x7f2b9a736820>
(Pdb) p node.body
[EmptyLine(tokens=[Token(EOL, '\n', 1, 0)]), Comment(tokens=[Token(COMMENT, '## Unit test file for cxta_ccdiff.py keywords', 2, 0), Token(EOL, '\n', 2, 45)]), Comment(tokens=[Token(COMMENT, '#', 3, 0), Token(EOL, '\n', 3, 1)])]
(Pdb) p node.header
None
(Pdb)
```

### Operating System

Linux

### Robocop version

2.0.0

**Comment by bhirsz** [comment]
Nevermind, I see it -> "Token(EOL, '\n', 1, 0)]), Comment..". So it starts with empty line that's why it tries to report the issue - but it fails due to section not having header ("hidden" ``*** Comments ***``).

**Comment by bhirsz** [comment]
For workaround you can try to exclude this rule (-e empty-line-after-section)
