### ISSUE TITLE
[Bug] robocop --report all return IndexError: list index out of range

### ISSUE THREAD

**Issue by jgdevrennes** [MarketSquare/robotframework-robocop#812]
### What happened?

When using "robocop --report all" execution faill with IndexError but it's working fine with robotframework-robocop version 2.7.0
Using robotframework==6.1a1

### What command/code did you try to run?

robocop --report all

### What is the full error message?

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\robocop.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\robocop\run.py", line 276, in run_robocop
    raise err
  File "C:\Python311\Lib\site-packages\robocop\run.py", line 264, in run_robocop
    linter.run()
  File "C:\Python311\Lib\site-packages\robocop\run.py", line 75, in run
    self.run_checks()
  File "C:\Python311\Lib\site-packages\robocop\run.py", line 120, in run_checks
    found_issues = self.run_check(model, str(file))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\robocop\run.py", line 138, in run_check
    for issue in checker.scan_file(ast_model, filename, source, templated)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\robocop\checkers\__init__.py", line 107, in scan_file
    self.visit_File(ast_model)
  File "C:\Python311\Lib\site-packages\robocop\checkers\__init__.py", line 112, in visit_File
    self.generic_visit(node)
  File "C:\Python311\Lib\ast.py", line 426, in generic_visit
    self.visit(item)
  File "C:\Python311\Lib\site-packages\robot\parsing\model\visitor.py", line 52, in visit
    visitor(node)
  File "C:\Python311\Lib\ast.py", line 426, in generic_visit
    self.visit(item)
  File "C:\Python311\Lib\site-packages\robot\parsing\model\visitor.py", line 52, in visit
    visitor(node)
  File "C:\Python311\Lib\ast.py", line 426, in generic_visit
    self.visit(item)
  File "C:\Python311\Lib\site-packages\robot\parsing\model\visitor.py", line 52, in visit
    visitor(node)
  File "C:\Python311\Lib\site-packages\robocop\checkers\spacing.py", line 809, in visit_Statement
    cont = [token for token in line if token.type == "CONTINUATION"][0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

### What did you expect to happen instead?

Log rules in console:
....
....
....

Processed xxx files from which xxx files contained issues.

Report generated by Robocop version: 2.7.0

Issues by ID:
Wxxx (line-too-long)                           : xxx
....

Found xxx issues: xxx WARNINGs, xx INFOs, x ERRORs.

Scan finished in xx.xxxs.

### Operating System

Windows

### Robocop version

Since version: 2.8.0

**Comment by mnojek** [comment]
Hey @jgdevrennes and thanks for your report.

The problem is actually in the W1015 `misaligned-continuation-row` rule, not in the reports.
Can you try to run `robocop -i 1015 <your_test_file>` and see if the issue still exists? It's important to find which test file actually causes Robocop to fail. It may be just a single file.

For us to be able to fix this bug, we need to be able to reproduce it, so if you can share with us the test that causes the issue, it'd be great and it will speed up providing a fix. If you can't, please come up with an example file that triggers the error. Most probably, it's the file where `...` continuation line is used, so you can narrow the search using this search query.

**Comment by jgdevrennes** [comment]
Sorry, I can't reproduce it, because I downgrade to 2.7.0 since to fix some rules (I didn't capture logs),
and now the problem is no longer present in v3.0.0
