### ISSUE TITLE
[Bug] Crash with `Set Test Variable` and escaped $, regression

### ISSUE THREAD

**Issue by Loch64** [MarketSquare/robotframework-robocop#829]
### What happened?

Crash 

### What command/code did you try to run?

```Robot
*** Test Cases ***
A
    Set Test Variable    \${a}    1
```

### What is the full error message?

```
> robocop demo.robot
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Scripts\robocop.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\run.py", line 276, in run_robocop
    raise err
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\run.py", line 264, in run_robocop
    linter.run()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\run.py", line 75, in run
    self.run_checks()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\run.py", line 120, in run_checks
    found_issues = self.run_check(model, str(file))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\run.py", line 138, in run_check
    for issue in checker.scan_file(ast_model, filename, source, templated)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\checkers\__init__.py", line 107, in scan_file
    self.visit_File(ast_model)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\checkers\__init__.py", line 112, in visit_File
    self.generic_visit(node)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 426, in generic_visit
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robot\parsing\model\visitor.py", line 49, in visit
    visitor(node)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 426, in generic_visit
    self.visit(item)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robot\parsing\model\visitor.py", line 49, in visit
    visitor(node)
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 426, in generic_visit
    self.visit(item)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robot\parsing\model\visitor.py", line 49, in visit
    visitor(node)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\checkers\naming.py", line 705, in visit_KeywordCall
    normalized_var_name = remove_nested_variables(var_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\demo-TxcuOVse-py3.11\Lib\site-packages\robocop\utils\misc.py", line 94, in remove_nested_variables
    return var_name.strip()
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
Fatal exception occurred. You can create an issue at https://github.com/MarketSquare/robotframework-robocop/issues/new/choose - Thanks!
```

### Robocop version

3.1.0

**Comment by bhirsz** [comment]
Thanks for the report, I confirm the regression. It's already fixed in the linked PR and will be released as 4.1.1 after merging it.
