### ISSUE TITLE
[Bug] crash on robotframework 7.0a1

### ISSUE THREAD

**Issue by DetachHead** [MarketSquare/robotframework-robocop#991]
### What happened?

robocop crashes on robotframework 7.0a1

### What command/code did you try to run?

```
robocop .\foo.robot
```

### What is the full error message?

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\project\.venv\Scripts\robocop.exe\__main__.py", line 4, in <module>
  File "C:\Users\user\project\.venv\Lib\site-packages\robocop\__init__.py", line 2, in <module>
    from robocop.config import Config
  File "C:\Users\user\project\.venv\Lib\site-packages\robocop\config.py", line 21, in <module>
    from robocop.rules import RuleSeverity
  File "C:\Users\user\project\.venv\Lib\site-packages\robocop\rules.py", line 36, in <module>
    from robocop.utils import ROBOT_VERSION
  File "C:\Users\user\project\.venv\Lib\site-packages\robocop\utils\__init__.py", line 5, in <module>
    from robocop.utils.file_types import FileType, FileTypeChecker
  File "C:\Users\user\project\.venv\Lib\site-packages\robocop\utils\file_types.py", line 12, in <module>
    from robocop.utils.misc import rf_supports_lang
  File "C:\Users\user\project\.venv\Lib\site-packages\robocop\utils\misc.py", line 20, in <module>
    from robot.variables.search import VariableIterator, search_variable
ImportError: cannot import name 'VariableIterator' from 'robot.variables.search' (C:\Users\user\project\.venv\Lib\site-packages\robot\variables\search.py). Did you mean: 'VariableError'?
```

### What did you expect to happen instead?

no crash

### Operating System

windows 10

### Robocop version

4.2.1

**Comment by bhirsz** [comment]
Thanks for the report. I'm entirely expecting various backward incompatible changes from 7.0 due to amount of changes. Didn't expect VariableIterator to change place but it is not part of the public API so I can't complain :) I will also try to run our unit tests with 7.0a1 soon to see what else require fixing.

**Comment by bhirsz** [comment]
The culprit: 

https://github.com/robotframework/robotframework/commit/2e93178286fff78bec12e0c3a8c9df3c6e2aaf1c

We will need to rewrite the variables handling in both Robocop and Robotidy. Since we still want to support previous RF versions I will create some kind of interface that will convert pre7 VariableIterator to work like RF7 VariableMatches and adjust our code for that.
